language: go
sudo: true
install: true
go:
    - 1.6.3
    - 1.7.1
    - tip
env:
    - GOARCH=amd64

install:
    - go get golang.org/x/tools/cmd/goimports
    - go get github.com/jjh2kiss/netlinkconnector
    - go get github.com/urfave/cli
    - go get golang.org/x/net/context

before_script:
    # make sure we keep path in tact when we sudo
    - sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers

script:
    - goimports -d ./
    - go vet ./...
    - sudo -E go test ./...
    - go build
